-- SUPERSEDED por 20260829181000_drop_entries_select_public.sql, que já foi
-- aplicado no banco. Este arquivo nunca teve efeito (tudo comentado) e fica
-- apenas como registro histórico.
--
-- drop policy if exists entries_select_public on public.entries;
